// export const ADD_CONTACT_LOADING = "ADD_CONTACT_LOADING";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";

// export const GET_CONTACT_LOADING = "GET_CONTACT_LOADING";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";

export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_ERROR = "EDIT_CONTACT_ERROR";
